viaa:
    logging:
        level: DEBUG
app:
    environment: !ENV ${APP_ENVIRONMENT}
    rabbitmq:
        user: !ENV ${RABBIT_MQ_USER}
        passwd: !ENV ${RABBIT_MQ_PASSWD}
        host: mq-qas.do.viaa.be
        port: 5672
        incoming:
            queue: !ENV ${S3_EVENTS_QUEUE}
            exchange: !ENV ${S3_EVENTS_EXCHANGE}
        outgoing:
            queue: !ENV ${FILETRANSFER_QUEUE}
            exchange: !ENV ${FILETRANSFER_EXCHANGE}
    pid-service:
        host: http://do-qas-mvn-01.do.viaa.be:8080/pid-qas
    mediahaven:
        ftp:
            host: ftp://dg-qas-tra-01.dg.viaa.be/
            user: !ENV ${MEDIAHAVEN_FTP_USER}
            passwd: !ENV ${MEDIAHAVEN_FTP_PASSWD}
    mediahaven-api:
            host: https://archief-qas.viaa.be/mediahaven-rest-api/resources/
            user: !ENV ${MEDIAHAVEN_API_USER}
            passwd: !ENV ${MEDIAHAVEN_API_PASSWD}
    organisations-api:
        host: http://do-qas-esb-01.do.viaa.be:10003/api/
    essence-destination-folder: DISK-SHARE-EVENTS
    collateral-destination-folder: DISK-SHARE-EVENTS
